#!/bin/sh
#
# test.sh <CPU> <OS> <hex>
#  CPU: 21064, 21164, 21264
#  OS: NT, UNIX, VMS
TMPDIR="."
cd `dirname "$0"`
SLADIR=$(cd ../data/languages; pwd)
CPU=$1
OS=$2
shift 2
for i in $@; do
  j=$(basename $i .hex);
  echo -n "$i ";
  hex=$(grep -v ^\# $i | tr -d " \n");
  out=$j.out$OS;
  $(sleigh-lift disassemble $SLADIR/$CPU$OS.sla $hex > $out);
  if [ -f $j.asm$OS ]; then
    diff -wu $j.asm$OS $out;
  else
    diff -wu $j.asm $out;
  fi;
  if [ $? -ne 0 ]; then
    echo "fail";
    break;
  else
    echo "pass";
    rm $out;
  fi;
done
